### ISSUE TITLE
How to pass function to options?

### ISSUE THREAD

**Issue by stefaneidelloth** [dermasmid/py-jsoneditor#3]
If I try to pass a function I get an error, that the function is not serializable.
Could you please add an example on how to pass functions? Maybe as string?

**Comment by dermasmid** [comment]
Thanks for opening an issue @stefaneidelloth,
If You want to pass a none serializable object the only way you can do that right now is by converting it the a JSON string yourself and passing the JSON string. You can do that by either replacing all none serializable objects with something else like a string representation for that object, or you can use `json.dumps` with the `default`  argument like so: `json.dumps([print], default= repr)`.

I will update `jsoneditor` to be able to do this automatically.

**Comment by stefaneidelloth** [comment]
If I pass the function as string, I get the error

![image](https://user-images.githubusercontent.com/12675339/143429888-33c0d971-2512-45f9-8e29-20a9367800e4.png)

=> Is there a way to actually execute a passed callback without changing the JavaScript code?
=> I am wondering how you got the callback working that is directly passed as argument to jsoneditor.editjson and if that strategy would also work for the callbacks that are passed as option.

**Comment by dermasmid** [comment]
Sorry, I thought you tried to pass a function as part of the JSON data (like a dict with function in it)
I looked over your code, and from what I understand you want to launch a window with some JSON data, halt the execution until the user edited the data and pressed the button, and then you want to take the data and return it from your function.
To do the you don't need threading event's because the `editjson` function halts the execution by default when you pass a callback function, and when you are ready to continue you can press the x button (which is right next to the check button) and that will continue the execution of the program which in your case will return the edited version of the JSON.
Edited you code to do just that:
```python
import jsoneditor


def edit(json_data):

    result = None
    def data_changed(adapted_json_data):
        nonlocal result
        result = adapted_json_data

    jsoneditor.editjson(json_data, data_changed)

    return result


print(edit([]))
```
Hope this helps.
